# Felipe Giuste
# 2021-10-01

## Ports ##
# SMART-on-FHIR Application (smart-on-fhir-app): 8300
# HAPI R4 FHRI Server (hapi-r4): 8301

version: "3.8"

# Persistent FHIR database
volumes:
    r4-database:

# Services
services:
    smartapp_template: ##------- SMART-on-FHIR Application -------##
        container_name: smartapp_template
        image: "fgiuste/node:15"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - NPM_CONFIG_LOGLEVEL=info
        volumes:
            - ./:/home/node/app
        ports:
            - "8300:3000"
        command: "/home/node/app/run_app.sh"
        stdin_open: true # docker run -i
        tty: true # docker run -t

    # hapir4_template: ##------- HAPI R4 FHIR Server -------##
    #     container_name: hapir4_template
    #     image: smartonfhir/hapi-5:r4-synthea
    #     environment:
    #         PORT: 8080
    #         HOST: 0.0.0.0
    #     ports:
    #         - "8301:8080"
    #     volumes:
    #         - "r4-database:/usr/local/tomcat/target/database:delegated"
    #     command: ["sh", "-c", "
    #         envsubst < /tmp/hapi.properties.tpl > /config/hapi.properties &&
    #         envsubst < /tmp/server.xml > /usr/local/tomcat/conf/server.xml &&
    #         catalina.sh run"]

    